name: hererwego
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fluttertoast: ^7.1.1
  shared_preferences: ^2.0.13
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4
  firebase_database: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
